version: "3.8"
services:
  php:
    build: .
    volumes:
      - .:/work

  nginx:
    build: ./nginx
    ports:
      - 8080:80

  mysql:
    image: mysql:8.0.21
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: pass
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql:
    driver: local
